spring:
  application:
    name: cubee-api 
server:
  port: ${PORT:5000}
logging:
  level:
    root: ERROR
app: 
  environment: test
  parameter-names:
    api-keys-path: "/${spring.application.name}/${app.environment}/api-keys/"
    openAiApiKeyPath: "/openai/${spring.application.name}/${app.environment}/api-key"
openai:
  chat: GPT_4_O_MINI
cors:
  allowed-origins:
    - http://localhost:3000
---
spring:
  config:
    activate:
      on-profile: test
cors:
  allowed-origins:
    - https://test.cubee.schf.me
---
spring:
  config:
    activate:
      on-profile: prod
app:
  environment: prod
cors:
  allowed-origins:
    - https://cubee.schf.me